---
- name: Create /etc/shouldidothat
  action: file path=/etc/shouldidothat state=directory owner=root group=root

- name: copy conf.json file to /etc/shouldidothat
  copy: src=keys/shouldidothat/conf.json dest=/etc/shouldidothat/conf.json owner=root group=root mode=0600

- name: stop shouldidothat service if exists
  service: name=shouldidothat state=stopped
  ignore_errors: yes

- name: remove shouldidothat-container if exists
  command: docker rm -f shouldidothat
  ignore_errors: yes

# - name: remove shouldidothat docker image if exists
#   command: docker rmi -f eljojo/shouldidothat
#   ignore_errors: yes

- name: pull eljojo/shouldidothat docker image
  command: docker pull eljojo/shouldidothat

- name: Set up shouldidothat service
  action: template src=shouldidothat.service.j2 dest=/lib/systemd/system/shouldidothat.service mode=0644 owner=root group=root

- name: enable shouldidothat service
  # service: name=shouldidothat enabled=yes
  command: systemctl enable shouldidothat.service

- name: reload systemd
  command: systemctl --system daemon-reload

- name: start shouldidothat service
  service: name=shouldidothat state=started
