---
- name: clone shouldidothat-docker repo
  git: repo=ssh://git@github.com/eljojo/shouldidothat-docker.git dest=/root/shouldidothat-docker accept_hostkey=true

- name: copy conf.json file
  copy: src=keys/shouldidothat/conf.json dest=/root/shouldidothat-docker/conf.json owner=root group=root mode=0600

- name: stop shouldidothat service if possible
  service: name=shouldidothat state=stopped
  ignore_errors: yes

- name: remove shouldidothat-container in case it exists
  command: docker rm shouldidothat-container
  ignore_errors: yes

- name: remove shouldidothat docker image in case it exists
  command: docker rmi shouldidothat
  ignore_errors: yes

- name: create shouldidothat docker image
  command: docker build -t shouldidothat . chdir=/root/shouldidothat-docker

- name: create shouldidothat docker container
  docker: image=shouldidothat name=shouldidothat-container state=present

- name: Set up shouldidothat service
  action: template src=shouldidothat.service.j2 dest=/lib/systemd/system/shouldidothat.service mode=0644 owner=root group=root
  notify: reload systemd

- name: enable shouldidothat service
  service: name=shouldidothat enabled=yes state=started
  # command: systemctl enable shouldidothat.service
